### ISSUE TITLE
chapter 5 - anova - bat10 dataset not found

### ISSUE THREAD

**Issue by maelfosso** [OpenIntroStat/openintro#14]
Hi,

Please I don't find **bat10** dataset use in the **ANOVA** of chapter 5 ``Inference for numerical data``

Where could I download it please ?

**Comment by DavidDiez** [comment]
Data set names don't always match up exactly from the books to the package. We often give things more descriptive names in the package since we have a larger set of data in the package, some of which can be quite similar, while we try to keep the names as simple as is reasonable in the book. You can find the official name of a data set by looking in the textbook source files, e.g. in this case, [here's the R file calling the data](https://github.com/OpenIntroOrg/openintro-statistics/blob/master/ch_inference_for_means/figures/mlbANOVA/mlbANOVA.R) to generate the figures, which calls the [mlbBat10](https://github.com/OpenIntroStat/openintro-r-package/blob/master/openintro/man/mlbBat10.Rd) data set.

There's also a data download link on the [OpenIntro website](http://www.openintro.org/os) (Data sets + R packages + LaTeX source) that contains a guide to which data sets are being used where.

**Comment by maelfosso** [comment]
@DavidDiez  thanks
