### ISSUE TITLE
As per the Korean font error

### ISSUE THREAD

**Issue by statkclee** [OpenIntroStat/openintro#25]
Hi,

When I render the image with Korean Character, the Korean characters are broken. 
-. myPDF in variable.R 

However, for instance, when I test the CairoPDF, the Korean characters are rendered correctly, but there are width and height issues.

![image](https://cloud.githubusercontent.com/assets/5325425/8855484/582c550e-31a0-11e5-8fec-20db83f8988a.png)

I think that the other asian characters will have similar issues when using openintro package.

Thank you.

**Comment by mine-cetinkaya-rundel** [comment]
See https://www.tidyverse.org/blog/2021/02/modern-text-features/ for some font enhancements in R. Instead of using `openintro::myPDF()` it might be more straightforward to use a different function for generating those images. I'll close this issue since it's not something we'll be fixing here, but if this is translation-related work and you'd still like help with getting the figures right, let me know and I can help figure out an alternative solution.
