### ISSUE TITLE
dotPlot() collides with mosaic::dotPlot()

### ISSUE THREAD

**Issue by rpruim** [OpenIntroStat/openintro#7]
From looking at your examples, I'm not exactly sure what the purpose of your `dotPlot()` is supposed to be, but it is unfortunate that you have chosen a name that conflicts with the version in the `mosaic` package, which makes the kind of dot plot often seen in introductory statistics courses.

``` r
mosaic::dotPlot( ~ rnorm(500), width = 0.1)
```

![image](https://cloud.githubusercontent.com/assets/722231/15331617/2806c94c-1c30-11e6-8c6f-3f54cc72fec9.png)

**Comment by mine-cetinkaya-rundel** [comment]
@rpruim I'm going through old issues and wanted to check if you think this is still a pain point. 

A bit of history -- `openintro::dotPlot()` made its way to CRAN before the first CRAN release of the mosaic package. That being said, I imagine `mosaic::dotPlot()` is more commonly used than `openintro::dotPlot()` since our student-facing teaching materials leverage either base R or ggplot2 functions, and this function is used to create a few figures in the textbook. So I'd be happy to deprecate and rename it in the next CRAN release (probably this summer) if the consensus is that this is creating difficulty for teaching.

**Comment by rpruim** [comment]
It is a pretty minor pain point now since (a) dotplots are a bit of a pain since they depend on the aspect ratio of the plot in ways that make autogenerating good dotplots awkward and (b) I've mostly moved away from {lattice} graphics altogether in favor of {ggplot2} or {ggformula} and I've been encouraging others to do the same.

The general issue of coexistence of packages with functions that have the same name keeps popping up, however.  I wish there were a better way to navigate this for beginners (and for package maintainers).

**Comment by mine-cetinkaya-rundel** [comment]
Totally agree! 

I'll close this for now, if it pops up again as an issue we can consider deprecating then.
